### PR TITLE
Updated tests to use inspec

### LINKED ISSUE #13: Change tests to inspec from serverspec
I would like to migrate our tests over to inspec, most of it should be extremely easy to port over. Inspec seems to be significantly more active in development than serverspec.  

|            | Date Range                  | Pulse      | Overview     |
| :--------- | :----------------------:    | :--------: | :----------- |
| inspec     | April 9, 2017 – May 9, 2017 | [Pulse](https://github.com/chef/inspec/pulse/monthly) | Excluding merges, 20 authors have pushed 85 commits to master and 91 commits to all branches. On master, 139 files have changed and there have been 5,579 additions and 2,685 deletions. |
| serverspec | April 9, 2017 – May 9, 2017 | [Pulse](https://github.com/mizzy/serverspec/pulse/monthly) | There hasn’t been any commit activity on mizzy/serverspec in the last month. |

### PR DESCRIPTION
**Pull request by joshuacherry**
This should resolve #13 . We may want to create a new issue for testing server.properties with the [ini](https://www.inspec.io/docs/reference/resources/ini/) resource.

### CODE REVIEW

**Review by benwebber — COMMENTED** [review]
This is just fantastic. I'm glad it's so easy to switch.

Two comments:

1. Chef actually offers proper yum and apt repos, which will do the file integrity verification for us:

    https://docs.chef.io/packages.html

    We could `ADD` the repo definitions and GPG keys to the Docker image, then install inspec as a normal package.
2. Mind updating the README to replace Serverspec?

**Comment by joshuacherry** [comment]
Functionally speaking, is there that big of a difference between the `sha256sum` I'm doing on the package I download and verifying the chef.asc file before using the repository?  
  
Alternatively, I could have the gpg key static in the dockerfile but that key is 34 lines of code vs the 64 digit sha256 that I have static in the Dockerfile.

I'm fine using either method, however i think what I've configured so far is _slightly_ more secure per line of code used, unless we want to trust `wget -qO - https://packages.chef.io/chef.asc | sudo apt-key add -` as "secure".

**Comment by benwebber** [comment]
> Alternatively, I could have the gpg key static in the dockerfile but that key is 34 lines of code vs the 64 digit sha256 that I have static in the Dockerfile.

Sorry, I wasn't quite clear. I mean storing the signing key and repo definitions in the `docker/` directory, then copying them into the image on build.

**Comment by joshuacherry** [comment]
Jessie doesn't seem to have the inspec package in their repo so I switched that 1 back to my previous method for now. Trusty is having a weird error that I cannot replicate locally yet. Travis error is `"*** WARNING *** You are not using Java 8`

**Comment by joshuacherry** [comment]
@benwebber This branch looks good to merge now, thanks for addressing Java 8.

**Comment by benwebber** [comment]
No problem. I had to fuss with the variables a bit, but basically we install Java 8 everywhere except 14.04 now.

**Pull request merged**
